name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autenticação no Docker Hub
        run: echo "Executanto o comando Docker login"
      - name: Construção da Imagem Docker
        run: echo "Executanto o comando Docker build"
      - name: Envio da Imagem Docker
        run: echo "Executanto o comando Docker push"
  
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticação na AWS
        run: echo "Executanto o comando aws configure"
      - name: Configuração do kubectl
        run: echo "Executanto o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executanto o comando kubectl apply"

